### ISSUE TITLE
RfC: yaml support for static routes

### ISSUE THREAD

**Issue by ninsky** [prestaconcept/PrestaSitemapBundle#103] opened 2016-05-22 07:14 UTC
Hi

I'm defining routes in yaml files. Would be great if I could add a sitemap=true option to these static  routes to add them automatically to my generated sitemap. 

I'm not sure if this bundle is still maintained. 

BR
ninsky

**Comment by CharlyPoppins** [comment] 2016-06-02 18:13
+1

**Comment by yann-eugone** [comment] 2016-06-07 12:14
Hi, this bundle is still maintained, sorry for answering so late.
I used to configure my routes using YAML too, but i have no problem.
Do you encounter some issues ?

**Comment by CharlyPoppins** [comment] 2016-06-07 14:19
In my case I try to use @Route for static routes and SitemapListenerInterface for my dynamic routes.

Then static routes does not appear in the generated sitemap.

**Comment by yann-eugone** [comment] 2016-06-08 13:45
I made a try with a routing config file like the following : 

```yml
yml_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    options:
        sitemap: true
```

and it works just fine...

**Comment by CharlyPoppins** [comment] 2016-06-09 12:35
I tried this :
```
site_about:
    path: /qui-sommes-nous
    defaults: { _controller: SiteBundle:Default:About }
    options:
        sitemap: true
```
combine to the SitemapListener :
````
public function populateSitemap(SitemapPopulateEvent $event)
{
	// my loop
$event->getGenerator()->addUrl($urlLang, $localeCourante);
	//
}
```

URL from the routing.yml are not generated neither in sitemap.xml nor sitemap.fr.xml
I've only got URL generated by the SitemapListener

maybe I have to configure something due to multiple locales ? also I'm using JMSI18nRoutingBundle

**Comment by yann-eugone** [comment] 2016-06-15 07:39
Hum, I'm not sure that the problem is on our side.
We added some documentation about YAML or XML routes to be defined in the sitemap (see README on master branch).
To be honest, I tried XML, YAML and Annotation routing in the same project, and it works like a charm.

I think that you have a problem in your code, but with the piece you pasted here, I cannot help...

**Comment by yann-eugone** [comment] 2017-11-22 18:32
@ninsky as I said, I have no problem with `YAML` routes. I'm closing this issue.
@CharlyPoppins if there is something with `JMSI18nRoutingBundle` please open an other issue.

**Closed by yann-eugone** 2017-11-22 18:32 UTC
