### ISSUE TITLE
Error on dump with directory in sitemap_file_prefix wi

### ISSUE THREAD

**Issue by potibm** [prestaconcept/PrestaSitemapBundle#278] opened 2021-04-15 20:29 UTC
**PHP version(s) affected**: 8.0.2

**Package version(s) affected**: 2.5.0

**Description**  
Calling `bin/console presta:sitemaps:dump` while setting 

```
dump_directory: public/sitemap
sitemap_file_prefix: sitemap/sitemap
```

(so basically trying to dump all sitemaps files into one subdir)

leads to an error:

```
In Dumper.php line 116:

  Warning: file_put_contents(/var/folders/7f/mf1fnqns62xf9wc9qwclp15r0000gn/T/PrestaSitemaps-60789f5d6f062/sitemap/sitemap.xml):
  Failed to open stream: No such file or directory
```

**How to reproduce**  
see above

**Possible Solution**  
Destination for writing the sitemap index probably needs to strip the directories, e.g.

```
file_put_contents($this->tmpFolder . '/' . basename($this->sitemapFilePrefix) . '.xml', $this->getRoot()->toXml());
```          

(this will probably fail for deeper directory structures)

**Note**
I hope that my approach makes any sense, sorry for bugging in case I am totally wrong.

**Comment by yann-eugone** [comment] 2021-04-16 09:10
Hi @potibm 🙂
Did you had a look to #196 ? Did it sound like it's somehow related ?
This looks like a "dump in a subdir issue" to me.

**Comment by potibm** [comment] 2021-04-16 12:21
@yann-eugone thanks. you are right. my ticket seems to be a duplicate. sorry.

**Comment by yann-eugone** [comment] 2021-04-16 12:32
Don't be, your description add some intel to the issue.
The fact that you are also having the issue is also relevant that the use cad might not be that edged.

Can you explain why you need something like that ?

**Comment by potibm** [comment] 2021-04-16 20:43
I guess the error occured because I was approaching two things at once:

- changing the output into a dedicated sitemap-folder (as i am using deployer)
- switching to dump (from dynamic)

the first point was easily resolved using the "sitemap_file_prefix" (still in dynamic mode). using the dump let to the error above.

removing both config entries and passing *both* target and --base-url seems to work now.

to be honest i would assume that both options work, e.g. the dynamic controller for a dev environment and dump for prod. so configuration only through .ini would be preferred.

but just my 2cent. i am happy that everything seems to work now :)  thanks for the great bundle!

**Comment by yann-eugone** [comment] 2024-01-24 12:39
Closing as duplicate of #196

**Closed as completed by yann-eugone** 2024-01-24 12:39 UTC
Labels: bug, duplicate
