### ISSUE TITLE
Urlset->add() doesn't use Url->lastmod() for the Urlset lastmod

### ISSUE THREAD

**Issue by dkarlovi** [prestaconcept/PrestaSitemapBundle#327] opened 2023-12-08 18:01 UTC
**PHP version(s) affected**: 8.2.13

**Package version(s) affected**: 3.3.1

**Description**  

```php

$set = new Urlset('/sitemap-set.xml');
$set->add(new UrlConcrete('http://example.com', new \DateTimeImmutable('2021-12-31 00:00:00'));
$set->add(new UrlConcrete('http://example.com', new \DateTimeImmutable('2022-12-31 00:00:00'));
$set->add(new UrlConcrete('http://example.com', new \DateTimeImmutable('2023-12-08 00:00:00'));

var_dump($set->getLastmod()); // should use the latest timestamp, but uses "now"
```

**How to reproduce**  

See above.

**Possible Solution**  

Set the lastmod on each added URL if higher than current.

**Additional Context**  

This allows reproducible builds for sitemaps, for example in functional tests.

**Comment by yann-eugone** [comment] 2023-12-13 16:20
Hello, thanks for the report
Seems that you are using the code by yourself, and Urlset as a constructor arg to acquire the lastmod
The "now" value is a fallback when you provide nothing

On the other hand, the bundle tries to provide a value from children when dumping it
Have you also the issue while using the bundle and not the API?

**Comment by dkarlovi** [comment] 2023-12-14 10:00
@yann-eugone I'm not using the bundle fully, I'm [using the `Urlset` as I'm streaming through my dataset](https://github.com/sigwinhq/yassg/blob/main/src/Generator.php#L80). Since the `Urlset` is a collection of `Url`, it stands to reason it itself doesn't have a last modified, the URLs it contains do, and its last modified is the most recent last modified of any URL it contains, no?

**Comment by yann-eugone** [comment] 2024-01-04 08:04
I understand your point, but because it is not a bug **in the bundle itself**, and because I'm unsure of the potential side effects of adding such change in the `Urlset` at runtime, I will close this issue.

I suggest you find a workaround **on your side** to recreate the `Urlset` after you get the date you want.

**Closed as completed by yann-eugone** 2024-01-04 08:04 UTC
Labels: bug

**Comment by jr-k** [comment] 2025-01-31 01:04
This definitely seems incorrect. If I add a URL to a section while providing a lastmod for each URL, I end up with "now" on UrlSet but it should take highest one. The generator isn’t functioning properly. The side effect isn’t too severe since it only affects lastmod, but the implementation is flawed.

Impossible to addUrlSet and/or set lastMod to UrlSet. Hard to override this because it's not only on Generator class but on model too.
